Website redesign edits
patternfly/patternfly-org pull request #2085
Opened 2020-09-10 00:14 UTC by gdoyle1

Making changes based on this spreadsheet https://docs.google.com/spreadsheets/d/1OXyPYyxy5fbo8tVw9-P9Uve8CM_CUP-BDzz8DEoeQoc/edit?usp=sharing

2020-09-10 00:15 UTC, gdoyle1 commented
@redallen not 100% sure why this is pulling my old commits in?

2020-09-10 00:16 UTC, patternfly-build commented
PF3 preview: https://patternfly-org-pr-2085-v3.surge.sh/v3

2020-09-10 13:30 UTC, redallen requested changes
Just one incorrect link

2020-09-10 17:43 UTC, gdoyle1 commented on packages/v4/src/content/design-guidelines/components/toolbar/toolbar.md
> +A search filter is intended to be used with a filter group as shown below when you want to include a single search field together with one or more select filters. It includes an 8px spacer to the rig
Fixing!

2020-09-11 20:56 UTC, mmenestr commented
Looks good Gina! The only problem I see is with the gif file in the progress bar documentation. @redallen how do we fix that?

2020-09-14 15:41 UTC, gdoyle1 commented
@redallen can't figure out how to fix that GIF ... it's in the img folder and i think i brought it into the documentation properly so not sure

2020-09-14 16:01 UTC, redallen commented
#2104 will give you the support you want.

In the meantime you could just import the gif manually using webpack.

```jsx
import myGif from './my-gif.gif';

<img src={myGif} width="500" height="300" />
```

2020-09-14 18:04 UTC, redallen commented
@gdoyle1 You'll have to merge or rebase the latest master for the `<img src="./my-gif.gif" width="500" height="300" />` to work.

2020-09-14 18:57 UTC, mmenestr approved these changes

2020-09-14 19:02 UTC, redallen approved these changes

2020-09-14 19:02 UTC, merged

2020-09-14 19:13 UTC, patternfly-build commented
Your changes have been released in: 
 - patternfly-org-4@4.2.8

Thanks for your contribution! :tada: