Chore/1723 add GitHub link
patternfly/patternfly-org pull request #2243
Opened 2020-10-30 16:14 UTC by evwilkin

Closes #1723 

This PR:
- changes the "Contribute" CTA on the homepage to "Github" and links to github.com/patternfly
- adds a Github icon to the masthead which also links to the PF Github page

2020-10-30 16:15 UTC, patternfly-build commented
PF3 preview: https://patternfly-org-pr-2243-v3.surge.sh/v3

2020-10-30 18:55 UTC, mcarrano reviewed
I see what you mean @evwilkin . Is there a way to set a min-width on the button to force it to be the same as the Get Started button? You can also try adding the GitHub icon in front of the label that will make it wider. @mceledonia any other idea?

2020-10-30 19:21 UTC, evwilkin commented
@mcarrano I like your suggestion of adding the GH logo to the CTA, I've made that update and will follow up with @mceledonia when he's back online.

2020-10-30 21:13 UTC, mcarrano commented
I like that better, too!

2020-11-04 17:27 UTC, evwilkin commented
@mceledonia was hoping to get your input on this mockup with the Github CTA on the homepage and the Github icon linked at the top of the page - we had discussed this previously but hadn't seen anything put together yet:

- https://patternfly-org-pr-2243-v4.surge.sh/v4

2020-11-10 19:10 UTC, redallen requested changes

2020-11-10 19:10 UTC, redallen commented on packages/theme-patternfly-org/layouts/sideNavLayout/sideNavLayout.js
> +        </Text>
This doesn't take up the full width/height and it's difficult to click on. Maybe go with a button instead like the search icon?
![image](https://user-images.githubusercontent.com/47335686/98720409-7f071280-235e-11eb-8b2a-ff5afcdc7b2b.png)

2020-11-11 16:24 UTC, redallen requested changes
Can we move this to the right of the release dropdown? It feels a little weird that the search box moves the button around:
![image](https://user-images.githubusercontent.com/47335686/98836997-66efcb80-2410-11eb-9a7f-4daf0140f97e.png)

2020-11-11 16:47 UTC, evwilkin commented
@redallen I see what you mean about the icon being pushed around by Search - I've swapped it & the search icon/box but still think the version switcher (and the dropdown arrow beside it) make sense to keep as-is.

2020-11-11 16:52 UTC, redallen approved these changes
That's fine, LGTM!

2020-11-11 18:43 UTC, mcarrano approved these changes
This looks great!

2020-11-11 18:46 UTC, merged

2020-11-11 19:02 UTC, patternfly-build commented
Your changes have been released in: 
 - theme-patternfly-org@0.2.6
 - patternfly-org-4@4.2.76

Thanks for your contribution! :tada: