Add Developer Resources to nav, move docs from Get Started, update links
patternfly/patternfly-org pull request #2248
Opened 2020-11-01 16:23 UTC by evwilkin

Towards #2200 

This PR:
- Adds new Developer Resources section to the nav
- Moves several pages from Get Started to Developer Resources
- Updates links to these affected pages to point to their new location

2020-11-01 16:25 UTC, patternfly-build commented
PF3 preview: https://patternfly-org-pr-2248-v3.surge.sh/v3

2020-11-11 17:28 UTC, redallen requested changes
Should be good to go once React bumps Core and org bumps react-docs.

2020-11-11 17:28 UTC, redallen commented on packages/theme-patternfly-org/scripts/md/parseMD.js
> +  if (source==='developer-resources') console.log(routes[pageData.slug]);
Remove this line

2020-11-11 18:25 UTC, redallen approved these changes

2020-11-11 18:38 UTC, mcarrano approved these changes
Looks good @evwilkin !

2020-11-11 18:38 UTC, merged