fix scrollbars, anchor links, page section padding
patternfly/patternfly-org pull request #2291
Opened 2020-11-24 17:00 UTC by evwilkin

Closes #2185 

This PR:
- Hides TOC scrollbar to avoid double scrollbars
- Fixes anchor links on Table design guidelines
- Removes custom PageSection styling in favor of default styling

2020-11-24 17:02 UTC, patternfly-build commented
PF3 preview: https://patternfly-org-pr-2291-v3.surge.sh/v3

2020-12-03 14:55 UTC, redallen commented on packages/theme-patternfly-org/templates/mdx.js
> -        type={isSinglePage ? 'default' : 'nav'}
When we put the "HTML/React/Design" tabs in this section I believe it's technically a nav section. It's fine if we don't want to use it, but in that case I'm not sure why the variant exists at all.

2021-01-21 18:16 UTC, evwilkin commented on packages/theme-patternfly-org/templates/mdx.css
>    background-color: var(--pf-global--BackgroundColor--light-200);
Default likely could be used, but this was used to match design mockups for the site

2021-01-26 20:24 UTC, mcoker requested changes
This looks good! Noticed a few things though.

* This "data list" link at the bottom of the table design guidelines links to `[...]/data-lists` - should be `data-list`

<img width="570" alt="Screen Shot 2021-01-26 at 1 48 17 PM" src="https://user-images.githubusercontent.com/35148959/105900729-11c06080-5fe2-11eb-81fc-50937ad1f949.png">


* For these `#nav-content` and `:first-child` styles for the first page section, we have `.pf-m-fill` that will cause a section to `flex-grow: 1`, and `.pf-m-no-fill` that will keep it from growing. You could use `.pf-m-fill` here, though I'm not entirely sure why this section is set to grow... Also `.pf-m-light` will give it a white background.

<img width="914" alt="Screen Shot 2021-01-26 at 2 14 57 PM" src="https://user-images.githubusercontent.com/35148959/105900393-95c61880-5fe1-11eb-8cb3-4965c1db5031.png">

* `#main-content` could also use `.pf-m-fill`, and by default the page section will have a grey background color. It's a bit different than the one specified here though. I'm all for using the things built in to patternfly, but if that grey needs to be different then that's fine.

<img width="897" alt="Screen Shot 2021-01-26 at 2 15 25 PM" src="https://user-images.githubusercontent.com/35148959/105900521-c908a780-5fe1-11eb-89b8-54e03dfb2532.png">

* This footer section could use `.pf-m-no-fill`, and potentially the default page section padding instead of what's specified here. Then the padding will change as the rest of the page sections' padding changes, which may or may not be what you want. Seems like it would be fine using the default padding though.

<img width="918" alt="Screen Shot 2021-01-26 at 2 16 10 PM" src="https://user-images.githubusercontent.com/35148959/105900685-010fea80-5fe2-11eb-8d2f-c7482a911b8b.png">

2021-02-11 16:00 UTC, evwilkin commented
@mcoker FYI I took in your suggestions above but also found a better way to structure some of the components used that made more sense, so now the default spacing should be used that majority of the time rather than custom spacing overrides.  Note that the alignment falls into 3 categories which helped me check different use cases - Component section pages (w/menu below title), Guidelines section (title only), and Training pages.

2021-02-11 16:28 UTC, mcoker commented on packages/theme-patternfly-org/templates/mdx.js
> +      <div className={katacodaLayout? "ws-mdx-content-katacoda" : "ws-mdx-content pf-m-fill"}>
> `pf-m-fill`

This works on some component/layout elements (like `.pf-c-page__main-section`, or a child of `.pf-l-split`), but doesn't appear to be doing anything here, so not sure if you need it.

2021-02-11 16:41 UTC, mcoker commented
@mcarrano @mceledonia I'm curious what you think of how the tabs at the top of the page are aligned. It looks like the left side of the first tab text is aligned with the page gutter, though that's not how it's designed to work in the code anyways. We don't have a page section to wrap the tabs component to align it properly. Looking at our upcoming tabs demo design https://marvelapp.com/prototype/5fba0cj/screen/73740947, it looks like the left edge of the tab underline should be aligned with the left edge of the page gutter.

Here's what it looks like now:

#### big screen
<img width="502" alt="Screen Shot 2021-02-11 at 10 31 29 AM" src="https://user-images.githubusercontent.com/35148959/107667253-06616c00-6c55-11eb-9c30-98df5e2929e5.png">

#### small screen
<img width="469" alt="Screen Shot 2021-02-11 at 10 31 38 AM" src="https://user-images.githubusercontent.com/35148959/107667259-07929900-6c55-11eb-877a-41c3f87d55c2.png">

Here's what it looks like if I put it in a normal page section and remove the top and bottom padding (`.pf-c-page__main-section pf-m-light pf-u-pb-0 pf-u-pt-0`), which keeps the left/right gutter aligned with the other page sections, and allows the space between the title and tabs to match the page section padding which is 24px on large screens, 16px on small screens.

#### big screen
<img width="502" alt="Screen Shot 2021-02-11 at 10 39 01 AM" src="https://user-images.githubusercontent.com/35148959/107667830-9a333800-6c55-11eb-9816-286a99da8a52.png">


#### small screen
<img width="503" alt="Screen Shot 2021-02-11 at 10 39 10 AM" src="https://user-images.githubusercontent.com/35148959/107667838-9c959200-6c55-11eb-8256-f259205052e9.png">

wdyt?

2021-02-11 16:46 UTC, mcoker reviewed
Looks great! Left a comment about the tabs, would be good to get some design feedback about that. Also maybe in an upcoming sprint we can look at using the new sidebar layout to manage the TOC?

2021-02-11 19:45 UTC, mcarrano commented
I agree with @mcoker . The new tab alignment looks odd and I think it's better if the left edge of the highlight lines up with the edge of the content.

2021-02-11 22:10 UTC, mcoker approved these changes
👍👍

2021-02-11 22:10 UTC, merged

2021-02-11 22:12 UTC, mcarrano commented
Looks much better !