Add tooltip labels & hide Type column
patternfly/patternfly-org pull request #2379
Opened 2021-01-29 23:52 UTC by evwilkin

Closes #2223 

This PR:
- Adds new `Tooltip labels` column
- Adds tooltip labels to a handful of icons
- Hides the `Type` column, but still allows it to be searchable

2021-01-29 23:58 UTC, patternfly-build commented
PF4 preview: https://patternfly-org-pr-2379-v4.surge.sh/v4

2021-02-01 20:49 UTC, abigaeljamie requested changes
Thank you so much, Evan! 

Is there any way to make some space between the "Tooltip" column and the "React" column? They look a little squishy. Other than that, this looks great :)

2021-02-01 21:22 UTC, evwilkin commented
@abigaeljamie the padding between the columns is consistent, though some columns are more spread out as they're set to expand for their content to fit & the other columns are set to size down & wrap lines to fit. 

Rather than overriding the table column styling, how about if we move the Tooltip label column all the way to the right - this way the column title doesn't bump up against the column next to it, and as most of the rows for this column are empty it may make sense to have it be the last one listed:

![Screen Shot 2021-02-01 at 4 16 22 PM](https://user-images.githubusercontent.com/8651509/106519441-48e2b600-64a9-11eb-8c71-413e594e67c7.png)

2021-02-03 19:54 UTC, abigaeljamie commented
Thanks, Evan!

2021-02-03 19:54 UTC, abigaeljamie approved these changes

2021-02-03 20:00 UTC, merged