Updating get started - design instructions
patternfly/patternfly-org pull request #2429
Opened 2021-03-31 00:32 UTC by gdoyle1

This PR updates the get started for designers instructions so that it incorporates the proper details for non-Sketch users

2021-03-31 00:39 UTC, patternfly-build commented
PF4 preview: https://patternfly-org-pr-2429-v4.surge.sh/v4

2021-03-31 12:49 UTC, mmenestr commented on packages/v4/src/content/get-started/design.md
> +The PatternFly design kit was originally developed for [Sketch users](#Mac-users), but is now available for use through [any design application](#Non-mac-users).
the "any design application" link doesn't work because the "non" in "non mac users" needs to be sentence case!

2021-03-31 12:49 UTC, mmenestr commented on packages/v4/src/content/get-started/design.md
> +The design kit is a collection of Sketch assets that make it easy for designers to create hi-fi mockups that accurately represent PatternFly components and layouts. It works with Sketch libraries.To
missing a space between "To use it"

2021-03-31 12:51 UTC, mmenestr commented on packages/v4/src/content/get-started/design.md
> +3. Click Download Document to open the file. Then, click File → Save as template.
I feel like the buttons to click on should be italicized or something to differentiate them from the rest of the text. So in this case "Download document"

2021-03-31 12:51 UTC, mmenestr commented on packages/v4/src/content/get-started/design.md
> +5. Click Add library to Sketch on the bottom right to add the library. You'll be prompted with a modal. Click Add library to Sketch again. Sketch will show you the library in your preferences window.
Same thing here with italicizing "Add library to Sketch"

2021-03-31 12:52 UTC, mmenestr requested changes
Left some minor comments - after that should be good to go!

2021-03-31 14:26 UTC, mcarrano reviewed
Looks good @gdoyle1 . I did not find any further issues. I'm just wondering if we should be more consistent with how we name people using the Sketch library. In the introduction we talk about Sketch users, and then later "Mac users." Should we be consistent in talking about Sketch users? You could have a Mac and decide to use something other than Sketch.

2021-04-01 13:38 UTC, gdoyle1 commented
> Looks good @gdoyle1 . I did not find any further issues. I'm just wondering if we should be more consistent with how we name people using the Sketch library. In the introduction we talk about Sketch users, and then later "Mac users." Should we be consistent in talking about Sketch users? You could have a Mac and decide to use something other than Sketch.

I wasn't sure how to go about this either. Garrett had left a comment on the google doc proposal saying that even if you are a Mac user, you might not be a Sketch user. So that's why I generalized it in the beginning. @mcarrano @mmenestr I'm good with updating the headers to be `Sketch users` vs `Non-Sketch users`.

IMO our solution for `Non-Sketch users` is not great today and that's why I fear changing the section title there. Our design  kit for non-Sketch programs is not nearly as supported nor as efficient as the one we have for Sketch

2021-04-01 15:39 UTC, mmenestr commented on packages/v4/src/content/get-started/design.md
> +5. Click Add library to Sketch on the bottom right to add the library. You'll be prompted with a modal. Click Add library to Sketch again. Sketch will show you the library in your preferences window.
Need to bold the second instance of "Add library to sketch" too

2021-04-01 18:16 UTC, mcarrano submitted a review, later dismissed
Looks good to me!

2021-04-05 12:24 UTC, mmenestr approved these changes

2021-04-05 12:24 UTC, merged