change rocket icon
patternfly/patternfly-org pull request #2509
Opened 2021-06-02 17:26 UTC by mmenestr

closes #2508 

@mcarrano just updated the rocket icon used in the getting started empty state image due to a comment (described in iss #2508 ). Michael and I decided it was probably best/easiest to just switch to a different version of a rocket icon.

2021-06-02 17:33 UTC, patternfly-build commented
PF4 preview: https://patternfly-org-pr-2509-v4.surge.sh/v4

2021-06-02 17:58 UTC, mcarrano requested changes
I'm good with changing this. I never really liked that space shuttle icon anyway. But we should also update this image in that case:

<img width="900" alt="Screen Shot 2021-06-02 at 1 56 35 PM" src="https://user-images.githubusercontent.com/6619860/120529554-9bc27080-c3aa-11eb-9839-5393a5b95a21.png">

2021-06-02 18:51 UTC, mmenestr commented
@mcarrano yes! I think you may have opened the link before my second push went through because I did change the image - do you mind checking again?

2021-06-03 16:10 UTC, mcarrano approved these changes
Looks great. Thanks @mmenestr . I will merge.

2021-06-03 16:10 UTC, merged