Add documentation to promote beta promotion candidates for 2021.11
patternfly/patternfly-org pull request #2588
Opened 2021-07-10 02:39 UTC by nicolethoen

2021-07-10 02:47 UTC, patternfly-build commented
PF4 preview: https://patternfly-org-pr-2588-v4.surge.sh/v4

2021-07-12 13:24 UTC, evwilkin commented on beta-component-promotion/promotion-2021.11/beta-promotion-candidates.md
> +### Action List
```suggestion
### ActionList
```

2021-07-12 13:24 UTC, evwilkin commented on beta-component-promotion/promotion-2021.11/beta-promotion-candidates.md
> +### Inline Edit
```suggestion
### InlineEdit
```

2021-07-12 13:25 UTC, evwilkin commented on beta-component-promotion/promotion-2021.11/beta-promotion-candidates.md
> +### Label Group
```suggestion
### LabelGroup
```

2021-07-12 13:25 UTC, evwilkin requested changes
LGTM other than a few nits with making component name spacing consistent

2021-07-12 14:34 UTC, mcarrano commented
@nicolethoen I think we talked about holding on Tile since we are rethinking the selected states there. Otherwise this looks good. Can you remind me what this page is for? Is this just to share or is this something that is actually being added to the website?

2021-07-12 14:39 UTC, nicolethoen commented
@mcarrano good thought. I'll make not of Tile on our tracking and remove it from this.
It's just for reference and sharing - not going on the website - like release highlights.

2021-07-15 13:28 UTC, nicolethoen commented
@evwilkin @mcarrano any other thoughts before I merge this? :)

2021-07-15 13:59 UTC, evwilkin approved these changes
LGTM - thanks!

2021-07-15 15:32 UTC, mcarrano approved these changes
Looks good to me, also!

2021-07-19 18:56 UTC, merged