2021.10 release highlights
patternfly/patternfly-org pull request #2631
Opened 2021-08-06 19:37 UTC by mcarrano

This adds release highlights for 2021.10 including md file and images.

2021-08-06 19:42 UTC, patternfly-build commented
PF4 preview: https://patternfly-org-pr-2631-v4.surge.sh/v4

2021-08-06 19:48 UTC, evwilkin commented on release-highlights/release-highlights-2021.10/release-highlights.md
> +Adds a demo to show how to the new Helper text component to add password validation and a strength indicator to a password field.
```suggestion
Adds a demo to show how to use the new Helper text component to add password validation and a strength indicator to a password field.
```

2021-08-06 19:48 UTC, evwilkin commented on release-highlights/release-highlights-2021.10/release-highlights.md
> +The log viewer extension has been updated to support a dark mode and full screen viewing. Note that log viewer has been moved from the Components to the new Expensions area on the PatternFly website.
```suggestion
The log viewer extension has been updated to support a dark mode and full screen viewing. Note that log viewer has been moved from the Components to the new Extensions area on the PatternFly website.
```

2021-08-06 19:48 UTC, evwilkin commented on release-highlights/release-highlights-2021.10/release-highlights.md
> +* [Disabled tabs](https://github.com/patternfly/patternfly/issues/4257) - Add a disabled variant for the tabs component. The use can place a tooltip on a disabled tab as they would for other disabled
```suggestion
* [Disabled tabs](https://github.com/patternfly/patternfly/issues/4257) - Add a disabled variant for the tabs component. The user can place a tooltip on a disabled tab as they would for other disabled controls. 
```

2021-08-06 19:49 UTC, evwilkin requested changes
Just a few typos otherwise looks good 👍

2021-08-06 19:55 UTC, nicolethoen approved these changes
Is it worth pointing out the new code editors in the workspace? - Like the work Zack did to see the code for each example?

2021-08-06 20:20 UTC, mcarrano commented
@evwilkin @nicolethoen thanks for the review. I accepted all of your suggested changes and also added content to highlight the updates to the website including the new code editor and addition of the Extensions section. Please review again.

2021-08-06 20:37 UTC, evwilkin approved these changes
LGTM thanks!

2021-08-09 14:31 UTC, nicolethoen approved these changes

2021-08-09 14:31 UTC, merged