chore(CalendarMonth): updated a11y docs
patternfly/patternfly-org pull request #3290
Opened 2022-11-14 20:14 UTC by thatblindgeye

Closes #3288 

Added some verbiage about using `aria-current="date"` (this could also apply to timepicker, but with "time" instead). [Marking elements as the current one using aria-current](https://www.accessibility-developer-guide.com/examples/sensible-aria-usage/current/#intended-use) states to avoid it for "now" (when the article was written in 2018) and to instead use visually hidden text. 

Additionally, date ranges might be an issue as well. Would all dates in the range have `aria-current="date"`, would only the 'range start' and 'range end' dates have that (possibly plus a visually hidden text to differentiate), or would only visually hidden text be more appropriate in that case?

2022-11-14 20:22 UTC, patternfly-build commented
PF4 preview: https://patternfly-org-pr-3290-v4.surge.sh/v4

2022-12-08 22:10 UTC, srambach commented on packages/v4/patternfly-docs/content/accessibility/calendar-month/calendar-month.md
> +At a minimum, a calendar month should meet the following criteria:
Sounds good - I think you can remove it from the second item and just have it in the third.

2022-12-12 21:13 UTC, srambach approved these changes
Looks good, thanks! 📆

2022-12-15 21:26 UTC, jessiehuff approved these changes
Nice job as usual! :)

2022-12-19 14:43 UTC, nicolethoen requested changes
This needs to be updated to include the addition of the `inlineProps` prop for wrapping the calendar month when used inline.

2023-01-03 15:09 UTC, thatblindgeye commented
>This needs to be updated to include the addition of the inlineProps prop for wrapping the calendar month when used inline.

Ah good catch! Added that in, let me know what you think of the layout and additions

2023-01-04 14:31 UTC, nicolethoen submitted a review, later dismissed

2023-01-05 03:17 UTC, nicolethoen approved these changes

2023-01-11 16:59 UTC, jessiehuff approved these changes

2023-01-12 13:17 UTC, merged