Add filter and search definitions
patternfly/patternfly-org pull request #3334
Opened 2023-01-10 19:26 UTC by mcarrano

Add definitions for the terms Filter and Search to the UX-writing/Terminology page to address this issue: #3312

2023-01-10 19:32 UTC, patternfly-build commented
PF4 preview: https://patternfly-org-pr-3334-v4.surge.sh/v4

2023-01-10 21:35 UTC, abigaeljamie requested changes

2023-01-10 21:35 UTC, abigaeljamie commented on packages/v4/patternfly-docs/content/design-guidelines/content/terminology.md
> +**Search** (v.) Use to decribe the action of querying a data set to return a results list. Searching will always be applied against some criteria and may be narrow or broard.
```suggestion
**Search** (v.) Use to decribe the action of querying a data set to return a results list. Searching will always be applied against some criteria and may be narrow or broad. 
```  
Small typo, changed "broard" to "broad"

2023-01-10 21:37 UTC, mcarrano commented
@abigaeljamie @mmenestr I updated the Terminology page in the UX writing section to add definitions for Filter and Search as referenced in the issue. Please give it a look here: https://patternfly-org-pr-3334-v4.surge.sh/v4/ux-writing/terminology

2023-01-10 21:39 UTC, abigaeljamie commented
> @abigaeljamie @mmenestr I updated the Terminology page in the UX writing section to add definitions for Filter and Search as referenced in the issue. Please give it a look here: https://patternfly-org-pr-3334-v4.surge.sh/v4/ux-writing/terminology

Thanks, Matt! I submitted a review. I found 1 typo, but otherwise the terms look great (thank you for following the terms structure to a tee!).

2023-01-12 19:51 UTC, mmenestr commented on packages/v4/patternfly-docs/content/design-guidelines/content/terminology.md
> +**Filter**: (v.) Use to describe the action of narrowing a set of search results to show only items meeting a certain criteria. Filtering is mostly associate with card views like tables, lists, and c
Also maybe it's just me, but calling tables and lists types of "card views" seem odd to me... wondering if we could use a different word?

2023-01-13 20:18 UTC, mcarrano commented on packages/v4/patternfly-docs/content/design-guidelines/content/terminology.md
> +**Filter**: (v.) Use to describe the action of narrowing a set of search results to show only items meeting a certain criteria. Filtering is mostly associate with card views like tables, lists, and c
Yes, I think that is a typo

2023-01-13 20:37 UTC, mcarrano commented
@abigaeljamie @mmenestr I made the changes that you suggested. Can you review this one more time? Thanks.

2023-01-16 19:33 UTC, mmenestr approved these changes
LGTM!

2023-01-16 19:33 UTC, mmenestr commented
Once @abigaeljamie approves, I will merge !

2023-01-17 12:46 UTC, abigaeljamie approved these changes

2023-01-17 14:18 UTC, merged