chore: fixed links in correct file
patternfly/patternfly-org pull request #3564
Opened 2023-05-31 13:10 UTC by ashley-o0o

more links fixed
Closes https://github.com/patternfly/patternfly-org/issues/3437

2023-05-31 13:24 UTC, patternfly-build commented
PF4 preview: https://patternfly-org-pr-3564-v4.surge.sh/v4

2023-06-01 13:33 UTC, ashley-o0o commented
**What:** Closes [#3437](https://github.com/patternfly/patternfly-org/issues/3437)

2023-06-06 23:55 UTC, nicolethoen requested changes

2023-06-06 23:55 UTC, nicolethoen commented on packages/v4/patternfly-docs/content/design-guidelines/components/menu-toggle/menu-toggle.md
> +For more information about this component's usage, see the [dropdown](/components/menus/dropdown/design-guidelines), [select](/components/select/design-guidelines), and [menu](/components/menu/design
The urls for the select and menu links in this sentence also need to be updated.

2023-06-09 13:32 UTC, merged