docs: expands design guidelines for split layout.
patternfly/patternfly-org pull request #3674
Opened 2023-07-31 15:57 UTC by edonehoo

closes #3587

2023-07-31 16:10 UTC, patternfly-build commented
Preview: https://patternfly-org-pr-3674-site.surge.sh

2023-08-25 16:10 UTC, edonehoo commented on packages/documentation-site/patternfly-docs/content/design-guidelines/layouts/split.md
> +You can specify which split item fills the remaining container space. More than one item can be set to fill, and they will share the remaining space equally.
```suggestion
You can specify which split item fills the remaining container space. More than one item can be set to fill and they will share the remaining space equally.
```

2023-08-25 16:10 UTC, edonehoo commented on packages/documentation-site/patternfly-docs/content/design-guidelines/layouts/split.md
> +You can wrap a split item to ensure that it fits among other content in the viewport as it is resized.
```suggestion
You can wrap a split item to ensure that it properly fits alongside other content as the screen is resized.
```

2023-08-25 16:53 UTC, edonehoo commented
@lboehling @mmenestr initial drafts of the layouts design guidelines are ready if you two want to take a look & give feedback! I'll tag you on all of them just fyi when you get a lot of notifs. I couldn't find images for most layouts (and will need to confirm the ones I found with devs), so if you have ideas on where to grab some I'm all ears

2023-09-11 19:21 UTC, mmenestr commented on packages/documentation-site/patternfly-docs/content/design-guidelines/layouts/split.md
> +You can specify which split item fills the remaining horizontal space in the layout. More than one item can be set to fill, as, and they will share the remaining space equally.
I don't understand this sentence haha the "can be set to fill, as, and"

2023-09-11 19:35 UTC, mmenestr requested changes
just have 1 comment to review, otherwise looks good!

2023-09-12 15:34 UTC, edonehoo commented on packages/documentation-site/patternfly-docs/content/design-guidelines/layouts/split.md
> +You can specify which split item fills the remaining horizontal space in the layout. More than one item can be set to fill, as, and they will share the remaining space equally.
```suggestion
You can specify which split item fills the remaining horizontal space in the layout. More than one item can be set to fill, and they will share the remaining space equally.
```

2023-09-27 16:20 UTC, mmenestr approved these changes

2023-09-27 16:49 UTC, merged