docs: expands design guidelines for stack layout.
patternfly/patternfly-org pull request #3675
Opened 2023-07-31 16:06 UTC by edonehoo

closes #3588

2023-07-31 16:20 UTC, patternfly-build commented
Preview: https://patternfly-org-pr-3675-site.surge.sh

2023-08-24 19:55 UTC, edonehoo commented
I'm currently using placeholder images for examples. Need to get real UI images (or at least mock ups) from somewhere. 

LMK if the language around allowing multiple items to fill is correct. This is what I gathered from the notes I had, but I know the original stack description only mentioned one item filling.

2023-08-25 16:06 UTC, edonehoo commented on packages/documentation-site/patternfly-docs/content/design-guidelines/layouts/stack.md
> +You can specifiy which stack item fill the remaining vertical space in the layout. More than one items can be set to fill, and they will share the remaining space equally.
```suggestion
You can specify which stack item fill the remaining vertical space in the layout. More than one item can be set to fill and they will share the remaining space equally. 
```

2023-08-25 16:53 UTC, edonehoo commented
@lboehling @mmenestr

2023-08-29 21:09 UTC, mmenestr commented on packages/documentation-site/patternfly-docs/content/design-guidelines/layouts/stack.md
> +The stack layout does not wrap. If you need a layout that wraps, instead choose the flex, gallery, level, or split layout instead.
I feel like the way this is structured doesn't align well with the header. I'd say something like "User the stack layout when you do not need your layout to wrap. If you need a layout that wraps, instead.. etc"

2023-08-29 21:09 UTC, mmenestr commented on packages/documentation-site/patternfly-docs/content/design-guidelines/layouts/stack.md
> +You can specify which stack item fill the remaining vertical space in the layout. More than one item can be set to fill and they will share the remaining space equally.
Should this say which stack item fill**S**, not item fill? or am I reading it wrong

2023-08-29 21:10 UTC, mmenestr requested changes
left a couple comments!

2023-09-11 19:38 UTC, mmenestr approved these changes

2023-09-27 14:33 UTC, merged