docs(typography): updates typography guidelines as part of content audit
patternfly/patternfly-org pull request #3699
Opened 2023-08-09 14:26 UTC by edonehoo

closes #3694

2023-08-25 15:07 UTC, edonehoo commented
A few comments/questions:

1. I want to move the "patternfly text styles" subsections to H3 so that they'll appear in the TOC, but it doesn't look great right now. Would it be a difficult change to adjust the css to adapt to this updated structure? Or are there objections to this change?

2. Additionally, to make these H3s I removed `title` from `TitleLevel` and want to be sure that's okay 👀 

3. There's some red code within the grid at the end of the file. Not sure if that needs to be updated, or if it's fine to ignore.

2023-09-25 13:43 UTC, andrew-ronaldson requested changes
Looks like there is a small spacing issue following these tables. Looks like a tag isn't getting closed somewhere. <img width="796" alt="Screenshot 2023-09-25 at 10 39 59 AM" src="https://github.com/patternfly/patternfly-org/assets/28658548/95d7857b-2328-49a5-b9bd-24eef2968869">

2023-09-25 17:43 UTC, edonehoo commented on packages/documentation-site/patternfly-docs/content/design-guidelines/styles/typography/typography.md
```suggestion
<div class="--pf-v5-global--spacer--sm"
</div>
```

2023-09-25 17:43 UTC, edonehoo commented on packages/documentation-site/patternfly-docs/content/design-guidelines/styles/typography/typography.md
> +<div class="--pf-v5-global--spacer--sm"
```suggestion
<div class="--pf-v5-global--spacer--sm">
```

2023-09-25 18:40 UTC, edonehoo commented on packages/documentation-site/patternfly-docs/content/design-guidelines/styles/typography/typography.md
> +<div class="--pf-v5-global--spacer--sm">
```suggestion
<div class="--pf-v5-global--spacer--lg">
```

2023-09-25 18:40 UTC, edonehoo commented on packages/documentation-site/patternfly-docs/content/design-guidelines/styles/typography/typography.md
> +<div class="--pf-v5-global--spacer--sm">
```suggestion
<div class="--pf-v5-global--spacer--lg">
```

2023-09-25 18:40 UTC, edonehoo commented on packages/documentation-site/patternfly-docs/content/design-guidelines/styles/typography/typography.md
> +<div class="--pf-v5-global--spacer--sm">
```suggestion
<div class="--pf-v5-global--spacer--lg">
```

2023-09-25 18:40 UTC, edonehoo commented on packages/documentation-site/patternfly-docs/content/design-guidelines/styles/typography/typography.md
> +<div class="--pf-v5-global--spacer--sm">
```suggestion
<div class="--pf-v5-global--spacer--lg">
```

2023-09-25 18:41 UTC, edonehoo commented on packages/documentation-site/patternfly-docs/content/design-guidelines/styles/typography/typography.md
> +<div class="--pf-v5-global--spacer--sm">
```suggestion
<div class="--pf-v5-global--spacer--lg">
```

2023-09-25 18:42 UTC, edonehoo commented on packages/documentation-site/patternfly-docs/content/design-guidelines/styles/typography/typography.md
> +<div class="--pf-v5-global--spacer--sm">
```suggestion
<div class="--pf-v5-global--spacer--lg">
```

2023-09-26 20:12 UTC, edonehoo commented
@andrew-ronaldson it still looked wrong on my end, so I fiddled more, and it still doesn't look right. should the spacers method be working or do we just need to use <br>?

2023-10-04 16:48 UTC, evwilkin commented
@edonehoo I believe you're fighting against some code built into our template for typography page which is causing the spacing issues.  I've adjusted the template slightly based on what it looks like we're going for now (mostly moving the **Note** just below the heading name) and put up a draft PR #3769 to see if that looks to fix the issues here.

Once the preview link is available there feel free to let me know how it looks and we can get this PR updated accordingly 👍

2023-10-04 17:18 UTC, edonehoo commented
@evwilkin ah tysm that looks far better! Is it possible to also make each "X heading" heading an H3 so that they appear in the TOC? If not - I think the changes you made are fine & can be integrated

2023-10-04 21:47 UTC, evwilkin commented on packages/documentation-site/patternfly-docs/content/design-guidelines/styles/typography/typography.md
> +<div class="--pf-v5-global--spacer--lg">
```suggestion
<div class="pf-v5-u-mt-lg> 
```

2023-10-04 21:48 UTC, evwilkin commented on packages/documentation-site/patternfly-docs/content/design-guidelines/styles/typography/typography.md
> +<div class="--pf-v5-global--spacer--lg">
```suggestion
<div class="pf-v5-u-mt-lg">
```

2023-10-04 21:48 UTC, evwilkin commented on packages/documentation-site/patternfly-docs/content/design-guidelines/styles/typography/typography.md
> +<div class="--pf-v5-global--spacer--lg">
```suggestion
<div class="pf-v5-u-mt-lg">
```

2023-10-04 21:48 UTC, evwilkin commented on packages/documentation-site/patternfly-docs/content/design-guidelines/styles/typography/typography.md
> +<div class="--pf-v5-global--spacer--lg">
```suggestion
<div class="pf-v5-u-mt-lg">
```

2023-10-04 21:48 UTC, evwilkin commented on packages/documentation-site/patternfly-docs/content/design-guidelines/styles/typography/typography.md
> +<div class="--pf-v5-global--spacer--lg">
```suggestion
<div class="pf-v5-u-mt-lg">
```

2023-10-04 21:48 UTC, evwilkin commented on packages/documentation-site/patternfly-docs/content/design-guidelines/styles/typography/typography.md
> +<div class="--pf-v5-global--spacer--lg">
```suggestion
<div class="pf-v5-u-mt-lg">
```

2023-10-04 21:49 UTC, evwilkin commented on packages/documentation-site/patternfly-docs/content/design-guidelines/styles/typography/typography.md
> +<div class="--pf-v5-global--spacer--lg">
```suggestion
<div class="pf-v5-u-mt-lg">
```

2023-10-04 21:49 UTC, evwilkin commented on packages/documentation-site/patternfly-docs/content/design-guidelines/styles/typography/typography.md
> +<div class="--pf-v5-global--spacer--lg">
```suggestion
<div class="pf-v5-u-mt-lg">
```

2023-10-04 21:49 UTC, evwilkin commented on packages/documentation-site/patternfly-docs/content/design-guidelines/styles/typography/typography.md
> +<div class="--pf-v5-global--spacer--lg">
```suggestion
<div class="pf-v5-u-mt-lg">
```

2023-10-04 21:49 UTC, evwilkin commented on packages/documentation-site/patternfly-docs/content/design-guidelines/styles/typography/typography.md
> +<div class="--pf-v5-global--spacer--lg">
```suggestion
<div class="pf-v5-u-mt-lg">
```

2023-10-04 22:01 UTC, evwilkin commented
@edonehoo the TOC updates proved to be harder than they should!  I went ahead and pushed a few changes here to your PR, you had the right idea with the spacer but the className wasn't quite right so the spacing wasn't working correctly.

2023-10-05 11:46 UTC, andrew-ronaldson commented
Thanks for the spacer fix Evan. I saw they were the variable names and got side tracked looking for the appropriate classes.

2023-10-05 13:14 UTC, edonehoo commented
@evwilkin @andrew-ronaldson woo thank you both! I think this can be merged

2023-10-05 13:27 UTC, evwilkin approved these changes
LGTM 👏

2023-10-05 13:27 UTC, merged