feat(deps): version bump for 5.2.1 release
patternfly/patternfly-org pull request #3913
Opened 2024-03-05 18:28 UTC by wise-king-sullyman

Bump for our 5.2.1 patch release.

2024-03-05 18:30 UTC, evwilkin commented on packages/documentation-framework/versions.json
> +      "date": "2024-02-05",
```suggestion
      "date": "2024-03-05",
```

2024-03-05 18:31 UTC, evwilkin commented on packages/documentation-site/patternfly-docs/content/get-started/release-highlights.md
> +
```suggestion

<Divider />

```

2024-03-05 18:32 UTC, evwilkin commented on packages/documentation-site/patternfly-docs/content/get-started/release-highlights.md
> +- Issues with styles and intractability of cards in Chromium based browsers
```suggestion
- Issues with styles and inetractability of cards in Chromium based browsers
  - Additional details: https://github.com/orgs/patternfly/discussions/6381
```

2024-03-05 18:38 UTC, patternfly-build commented
Preview: https://patternfly-org-pr-3913-site.surge.sh

2024-03-05 19:28 UTC, wise-king-sullyman commented on packages/documentation-framework/versions.json
> +      "date": "2024-03-05",
```suggestion
      "date": "2024-03-01",
```

2024-03-06 14:14 UTC, edonehoo requested changes
Small edits mostly to adjust tense!

2024-03-06 14:14 UTC, edonehoo commented on packages/documentation-site/patternfly-docs/content/get-started/release-highlights.md
> +PatternFly 5.2.1 is now live! This was a patch release to fix the below bugs. Here are the package versions from this release.
```suggestion
PatternFly 5.2.1 is now live! This was a patch release to fix a few bugs that were found.
```

2024-03-06 14:14 UTC, edonehoo commented on packages/documentation-site/patternfly-docs/content/get-started/release-highlights.md
> +- Pass through of more props to monaco-editor in our code editor component
```suggestion
### Fixed bugs
In this patch release, we:
- Corrected issues with styles and intractability of cards in Chromium-based browsers.
  - Additional details: https://github.com/orgs/patternfly/discussions/6381
- Added support for status modifiers on modal titles.
- Updated types used in react-charts to reflect changes in the Victory types.
- Reverted a previous type change within our clipboard copy component that was unintentionally breaking.
- Updated our code editor component to pass through more properties to monaco-editor. 
```

2024-03-06 15:47 UTC, edonehoo approved these changes

2024-03-07 18:25 UTC, wise-king-sullyman commented on packages/documentation-framework/versions.json
> +        "@patternfly/react-component-groups": "5.0.0",
```suggestion
        "@patternfly/react-component-groups": "5.1.0",
```

2024-03-08 15:48 UTC, edonehoo approved these changes
Looks great!

2024-03-08 15:52 UTC, merged