feat(docs-framework): Update AutoLinkHeader to use the Text component
patternfly/patternfly-org pull request #4049
Opened 2024-05-30 18:48 UTC by wise-king-sullyman

Closes #4035

2024-05-30 18:55 UTC, patternfly-build commented
Preview: https://patternfly-org-pr-4049-site.surge.sh

2024-05-30 19:26 UTC, jessiehuff approved these changes

2024-05-30 22:27 UTC, mcoker requested changes
LGTM though the anchor link disappeared with removing `position: relative` from `.ws-heading`. Also if we wanna make the anchor icon the default icon color, the token for that is `var(--pf-t--global--icon--color--regular)`. Looks like the existing style is commented out, so the icon is inheriting its color from the parent `<a>` which is set to our link color https://github.com/patternfly/patternfly-org/blob/4b783773dc5f30f16820cfd33433aa6a8cfd4546/packages/documentation-framework/components/autoLinkHeader/autoLinkHeader.css#L2

Left another comment about the flex layout used around the autolinkheader and how that will keep any heading in it from applying margin from the content/text component since it's the only-child. Probably out of scope for this PR to do anything about, but probably worth looking at somewhere in this update of the org styles? At least the content heavy pages that likely will not have metadata could probably benefit from not having the parent flex layout that will enable the heading margin/spacing to apply.

FWIW Here's the [about ux writing page](https://patternfly-org-pr-4049-site.surge.sh/ux-writing/about-ux-writing/) if I move all of the headings out of the flex layouts, remove a random "undefined" string showing up in the classlist for the paragraphs and lists and things, and change the page title from a 4xl title to the content/text component's `<h1>` (that last one I'm assuming we don't want to do, the title is way too small)

<img width="2372" alt="Screenshot 2024-05-30 at 5 13 20 PM" src="https://github.com/patternfly/patternfly-org/assets/35148959/8772aee4-1936-4f4d-8b9a-f7fe4d4229c1">

And here's the page as it is in the PR for reference

<img width="2372" alt="Screenshot 2024-05-30 at 5 13 36 PM" src="https://github.com/patternfly/patternfly-org/assets/35148959/96ae0d81-d1d9-4e49-889b-8f093e033221">

2024-06-12 01:43 UTC, nicolethoen approved these changes

2024-06-17 16:13 UTC, mcoker approved these changes
LGTM! One thing we should follow up with is this little gap between the anchor and heading text, if you move your mouse slowly from the heading text to the anchor, the anchor will disappear

<img width="226" alt="Screenshot 2024-06-17 at 11 12 08 AM" src="https://github.com/patternfly/patternfly-org/assets/35148959/a878e3b7-da93-45cb-8c57-aff7aad70b8c">

2024-06-17 17:37 UTC, merged