fix: update styles on color page
patternfly/patternfly-org pull request #4157
Opened 2024-07-25 23:52 UTC by nicolethoen

Closes https://github.com/patternfly/patternfly-org/issues/4067
Closes https://github.com/patternfly/patternfly-org/issues/4073

2024-07-25 23:59 UTC, patternfly-build commented
Preview: https://patternfly-org-pr-4157-site.surge.sh

2024-07-29 13:47 UTC, edonehoo commented on packages/documentation-site/patternfly-docs/content/design-guidelines/styles/colors/colors.md
> +Our color palettes are organized into "families" that contain different shades of the same hue. In the following palettes, you can expand each value color or shadow in a family to see more details.
```suggestion
## Color families 
Our color palettes are organized into "families" that contain different shades of the same hue. In the following families, you can expand each color to see related tokens.
```

Did we decide to keep the color families in addition to linking out to the Red Hat palettes? I think I removed the whole section in my pr, so would update the text to something like this if we are going to keep them

2024-07-29 13:51 UTC, edonehoo commented
A few things I noticed: 

1. In dark mode, the text on the color families doesn't update and can't be read in some cases: 
<img width="285" alt="image" src="https://github.com/user-attachments/assets/4a17277a-2503-423c-9029-2f03994ec61f">

2. Also in the families, there are sometimes no tokens listed (which maybe there are just no tokens related to the color? but it looks like there should be some listed): 
<img width="287" alt="image" src="https://github.com/user-attachments/assets/4f619494-e8a1-4666-9307-727d4071b720">

3. Related to ^ Should we change the label from "CSS variables" to "Tokens" in the expanded family sections?

4. This is small, but the primary background color swatch has a background, even before you hover:
<img width="223" alt="image" src="https://github.com/user-attachments/assets/67e06a26-da69-4c4d-8ce4-8c265440898f">

2024-07-29 13:51 UTC, edonehoo commented on packages/documentation-site/patternfly-docs/content/design-guidelines/styles/colors/colors.md
> +<Divider/>
```suggestion
```

2024-07-30 00:50 UTC, nicolethoen commented
> 4\. This is small, but the primary background color swatch has a background, even before you hover:

That's because without a background color, the color swatch is invisible! 😆 I'm open to other color suggestions!

> Also in the families, there are sometimes no tokens listed (which maybe there are just no tokens related to the color? but it looks like there should be some listed):

I can make a 'no semantic tokens message if there are none?

2024-07-30 13:43 UTC, edonehoo commented
> That's because without a background color, the color swatch is invisible!
Oh, duh! 😆 I can't think of a different approach that's ~the golden ticket, so I think we can just stick with this one, just to get the info updated? And then maybe revisit with a designer to see if we want to change it

2024-07-30 13:45 UTC, edonehoo approved these changes
I like it 🗣️

2024-07-30 13:46 UTC, edonehoo requested changes

2024-07-30 13:46 UTC, edonehoo commented on packages/documentation-site/patternfly-docs/content/design-guidelines/styles/colors/colors.md
> +    <ColorFamily title="Cyan family" family="teal" />
```suggestion
    <ColorFamily title="Teal family" family="teal" />
```
wait, just noticed this. I think we call this teal now

2024-07-30 14:53 UTC, edonehoo approved these changes

2024-07-31 11:44 UTC, merged