fix(docs): fix gdpr banner, tokenize footer styles
patternfly/patternfly-org pull request #4167
Opened 2024-07-31 01:50 UTC by evwilkin

Closes #4061 

This PR:
- Replaces custom styles in footer.js with tokens, or removes completely where possible
- Fixes GDPR banner functionality (currently it always shows, is not dismissable)

2024-07-31 01:57 UTC, patternfly-build commented
Preview: https://patternfly-org-pr-4167-site.surge.sh

2024-07-31 14:57 UTC, kmcfaul approved these changes
Looks great! Glad to see some of the custom styling cleaned up!

2024-08-05 14:28 UTC, nicolethoen reviewed
I am not sure if a design issue ended up open to address footer styles. I'd love some design feedback on the footer ahead of final release. It could be a follow up issue to this, though.

I tagged @bekah-stephens for her input

2024-08-05 14:28 UTC, nicolethoen commented on packages/documentation-framework/components/footer/footer.css
> +  color: var(--pf-t--global--text--color--300);
can we use a sematic token here instead?

2024-08-05 14:28 UTC, nicolethoen commented on packages/documentation-framework/components/footer/footer.css
> +  background-color: var(--pf-t--color--gray--95);
and here?

2024-08-05 14:28 UTC, nicolethoen commented on packages/documentation-framework/components/footer/footer.css
> +  font-size: var(--pf-t--global--font--size--100);
not a semantic token

2024-08-07 18:20 UTC, bekah-stephens requested changes
Changes are looking good so far! Since we're updating tokens to use our new semantic versions, this would be a good chance to update the light theme version of the footer as well. Screenshot & token suggestions below!

![image](https://github.com/user-attachments/assets/22188a75-310b-47bc-b25a-f104b001a851)


1. footer (main section background) use _**--global--background--color--secondary--default**_
2. footer-menu-list-item use _**--global--text--color--subtle**_
3. footer-menu-link use _**--global--text--color--link--default**_
4. footer-column (box background) use _**--global--background--color--primary--default**_
5. update the PF logo to be the same coloring as in the masthead
6. footer-menu-about-description use _**--global--text--color--regular**_
7. footer-menu-social-link use _**--global--icon--color--brand--default**_

tagging @lboehling to double check my token suggestions

2024-08-20 17:29 UTC, evwilkin commented
Thanks @bekah-stephens your feedback was super helpful to get this corrected, hopefully everything matches what you suggested now!

2024-08-20 17:50 UTC, bekah-stephens approved these changes

2024-08-20 18:01 UTC, bekah-stephens requested changes
A few minor things:

- The footer menu list titles "Quicklinks" and "Contribute" are using the _**"Red Hat Display"**_ font family, while the "Stay in touch" title is using _**"Red Hat Text"**_. They should all be using **_"Red Hat Text"_**
- We're moving away from using all caps, so those three titles should be **_sentence case_** so that we're consistent with the design language type guidelines
- For all three titles use a **_"semibold" font-weight_** rather than "bold"

2024-08-22 20:54 UTC, evwilkin commented
Thanks @bekah-stephens & @lboehling - updated now with those changes 👍

2024-08-26 15:03 UTC, bekah-stephens approved these changes
Looks good!

2024-08-26 17:49 UTC, merged