fix(docs): switched from v4 to evergreen badge link
patternfly/patternfly-org pull request #4186
Opened 2024-08-13 12:36 UTC by rebeccaalpert

Fixes https://github.com/patternfly/patternfly-org/issues/4124.

2024-08-13 12:43 UTC, patternfly-build commented
Preview: https://patternfly-org-pr-4186-site.surge.sh

2024-08-13 18:08 UTC, gitdallas approved these changes

2024-08-13 18:21 UTC, mcoker approved these changes
LGTM. A little scope-creep but there is another link on this page that isn't absolute and doesn't take you to the correct page. Just needs a leading `/`

https://github.com/patternfly/patternfly-org/blob/65975ec5c0857f722a6a422e4cb27c2e8c901520/packages/documentation-site/patternfly-docs/content/design-guidelines/components/label/label.md?plain=1#L159

I wonder if we should try to dig up more of those?

2024-08-13 19:39 UTC, rebeccaalpert commented
> LGTM. A little scope-creep but there is another link on this page that isn't absolute and doesn't take you to the correct page. Just needs a leading `/`
> 
> https://github.com/patternfly/patternfly-org/blob/65975ec5c0857f722a6a422e4cb27c2e8c901520/packages/documentation-site/patternfly-docs/content/design-guidelines/components/label/label.md?plain=1#L159
> 
> I wonder if we should try to dig up more of those?

Sure! Added a leading backslash and fixed the typo there. I haven't looked for more links without slashes, but I am seeing more v4 links that just this. I did a search for `v4` in `./packages/documentation-site/patternfly-docs/content/design-guidelines` and saw some other hits.

2024-08-13 19:51 UTC, mcoker requested changes
So sorry, I didn't even read the a11y link you fixed. Looks like it's also pointing to jump-links a11y tab, and should point to the label tab instead

2024-08-13 19:51 UTC, mcoker commented on packages/documentation-site/patternfly-docs/content/design-guidelines/components/label/label.md
> +For information regarding accessibility, visit the [labels accessibility](/components/jump-links/accessibility) tab.
```suggestion
For information regarding accessibility, visit the [labels accessibility](/components/label/accessibility) tab.
```

2024-08-13 20:44 UTC, rebeccaalpert commented on packages/documentation-site/patternfly-docs/content/design-guidelines/components/label/label.md
> +For information regarding accessibility, visit the [labels accessibility](/components/jump-links/accessibility) tab.
No worries! All set.

2024-08-13 20:53 UTC, rebeccaalpert commented
No worries! Should be all set: https://patternfly-org-pr-4186-site.surge.sh/components/label/design-guidelines

2024-08-13 23:21 UTC, mcoker commented on packages/documentation-site/patternfly-docs/content/design-guidelines/components/label/label.md
> +For information regarding accessibility, visit the [labels accessibility](components/label/accessibility) tab.
Just need to add the leading slash back and I think it's set!

```suggestion
For information regarding accessibility, visit the [labels accessibility](/components/label/accessibility) tab.
```

2024-08-14 00:58 UTC, mcoker approved these changes
FABULOUS! 🤩

2024-08-20 21:10 UTC, nicolethoen approved these changes

2024-08-20 21:10 UTC, merged